site:
  title: Footing.Framework
  url: https://edertelhado.github.io/Footing.Framework
  start_page: footing-framework::index.adoc
content:
  sources:
    - url: .
      branches: HEAD
      start_path: docs
ui:
  bundle:
    url: ./docs/ui/ui-bundle.zip
output:
  dir: docs/build/site
runtime:
  fetch: true
asciidoc:
  attributes:
    icons: font
    source-highlighter: highlight.js
    sectanchors: true
    table-caption: false
    figure-caption: false
